version: '3'
services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql